### ISSUE TITLE
Open bookmarks from qc

### ISSUE THREAD

**Issue by husimo-tilleuls** [qownnotes/qc#7]
Hello, 

First of all, thank you for QOwnNotes and qc! It's working very nicely!

I would be great to be able to open bookmarks from terminal using `qc` (or another program named for example `qb` as bookmark URL is not a command but codebase could be close I think).

Indeed, it would "just necessitate" (I'm not technically a dev so maybe it's easy to say!) to pipe bookmark URL to the `open` command.

For me it would be much more practical than opening my webbrowser, then click on the extension, search my bookmark, open it.

Thank you so much!

**Comment by pbek** [comment]
Thank you for you kind words!

So basically you want a new terminal app that does the same as https://github.com/qownnotes/web-companion? 😆

**Comment by husimo-tilleuls** [comment]
Actually yes! And I didn't know on which repo create the issue lol.

I don't need all web-companion features though, just be able to browse bookmarks and open it, so I guess it would be closer to qc than web-companion.

Thank you

**Comment by pbek** [comment]
I really think browser bookmarks are a thing that can depend on a browser, just like terminal commands can depend on the terminal. :) So don't really see a use-case for a cli browser bookmark tool. :)
What is your use-case?

**Comment by husimo-tilleuls** [comment]
I like to use my mouse the least as possible. Everything I can do in my terminal or using a "command palette" like krunner (e.g. searching on a search engine or actually navigating through actual Firefox bookmarks) I do it using them. I'm not going to ask for a krunner addon as I guess it's something particular.

Maybe if I could use the web companion app only with keyboard shortcuts it would do the job but I can't seem to be able to trigger `Ctrl + Shift + B` to open the bookmarks popup on Firefox (it displays and hide the bookmarks bar). I just filled a separate issue for that : https://github.com/qownnotes/web-companion/issues/48

**Comment by pbek** [comment]
Since shortcuts do work in the browser extension let's best lets talk about that in https://github.com/qownnotes/web-companion/issues/48. 😉
